apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-database-management
  namespace: dnd
data:
  PGADMIN_DEFAULT_EMAIL: 'saarfire@gmail.com'
  PGADMIN_DEFAULT_PASSWORD: 'password'
  APPNAME: {{ .Chart.Name }}
  APPVERSION: {{ .Chart.AppVersion }}
  MESSAGE: "Hello from DND"
