apiVersion: v1
kind: Pod
metadata:
  name: db-{{ .Chart.Name }}-{{ .Chart.Version }}
  namespace: dnd
  labels:
    app: {{ .Chart.Name }}
spec:
  containers:
  - name: database
    image: quay.io/enterprisedb/postgresql #https://hub.docker.com/_/postgres/
    #imagePullSecrets:
    ports:
      - containerPort: 5432
    envFrom:
      - configMapRef:
          name: configmap-database

  - name: database-management
    image: quay.io/custom/pgadmin4 #docker.io/dpage/pgadmin4
    #imagePullSecrets:
    ports:
      - containerPort: 80 # we need to bind this one to port 8080 - use service and route to do that
    envFrom:
      - configMapRef:
          name: configmap-database-management

  